export const products = [
  {
    id: 1,
    name: "스테인리스 보온 텀블러",
    category: "텀블러/보온병",
    category1: "보온",
    category2: "350ml",
    season: "겨울 한정",
    volume: "350ml",
    price: "2만원 이하",
    imageUrl: "/images/tumbler1.jpg",
  },
  {
    id: 2,
    name: "플라스틱 보냉 텀블러",
    category: "텀블러/보온병",
    category1: "보냉",
    category2: "플라스틱",
    season: "여름 한정",
    volume: "500ml 이상",
    price: "2만원 이하",
    imageUrl: "/images/tumbler2.jpg",
  },
  {
    id: 3,
    name: "유광 스테인리스 텀블러",
    category: "텀블러/보온병",
    category1: "스테인리스",
    category2: "유광",
    season: "겨울 한정",
    volume: "500ml 이상",
    price: "2만원 이상",
    imageUrl: "/images/tumbler3.jpg",
  },
  {
    id: 4,
    name: "무광 스테인리스 텀블러",
    category: "텀블러/보온병",
    category1: "스테인리스",
    category2: "무광",
    season: "여름 한정",
    volume: "350ml",
    price: "2만원 이하",
    imageUrl: "/images/tumbler4.jpg",
  },
  {
    id: 5,
    name: "세라믹 머그컵",
    category: "머그/컵",
    category1: "머그",
    category2: "세라믹",
    season: "굿즈 기획전",
    volume: "350ml",
    price: "1만원 이하",
    imageUrl: "/images/mug1.jpg",
  },
  {
    id: 6,
    name: "스틸 머그컵",
    category: "머그/컵",
    category1: "머그",
    category2: "스틸",
    season: "굿즈 기획전",
    volume: "500ml 이상",
    price: "1~2만원",
    imageUrl: "/images/mug2.jpg",
  },
  {
    id: 7,
    name: "투명 컵",
    category: "머그/컵",
    category1: "컵",
    category2: "투명",
    season: "굿즈 기획전",
    volume: "350ml",
    price: "1만원 이하",
    imageUrl: "/images/cup1.jpg",
  },
  {
    id: 8,
    name: "컬러 컵",
    category: "머그/컵",
    category1: "컵",
    category2: "컬러",
    season: "굿즈 기획전",
    volume: "500ml 이상",
    price: "1~2만원",
    imageUrl: "/images/cup2.jpg",
  },
  {
    id: 9,
    name: "피크닉 매트",
    category: "라이프스타일",
    category1: "피크닉",
    category2: "",
    season: "봄 기획전",
    volume: "",
    price: "2만원 이상",
    imageUrl: "/images/picnic1.jpg",
  },
  {
    id: 10,
    name: "스타벅스 노트",
    category: "라이프스타일",
    category1: "문구",
    category2: "",
    season: "4월 신규코어 MD",
    volume: "",
    price: "1~2만원",
    imageUrl: "/images/stationery1.jpg",
  },
  {
    id: 11,
    name: "티 전용 필터",
    category: "티/커피용품",
    category1: "필터",
    category2: "",
    season: "",
    volume: "",
    price: "1만원 이하",
    imageUrl: "/images/filter1.jpg",
  },
  {
    id: 12,
    name: "티스푼 세트",
    category: "티/커피용품",
    category1: "티스푼",
    category2: "",
    season: "",
    volume: "",
    price: "1만원 이하",
    imageUrl: "/images/teaspoon1.jpg",
  },
  {
    id: 13,
    name: "딸기 생크림 케이크 (홀)",
    category: "케이크",
    category1: "홀케이크",
    category2: "",
    season: "봄 기획전",
    volume: "",
    price: "2만원 이상",
    imageUrl: "/images/cake1.jpg",
  },
  {
    id: 14,
    name: "녹차 롤케이크 (조각)",
    category: "케이크",
    category1: "조각",
    category2: "",
    season: "4월 신규코어 MD",
    volume: "",
    price: "1만원 이하",
    imageUrl: "/images/cake2.jpg",
  },
  {
    id: 15,
    name: "미니 초콜릿 세트",
    category: "초콜릿/스낵",
    category1: "초콜릿",
    category2: "",
    season: "",
    volume: "",
    price: "1만원 이하",
    imageUrl: "/images/choco1.jpg",
  },
  {
    id: 16,
    name: "쿠키 믹스",
    category: "초콜릿/스낵",
    category1: "쿠키",
    category2: "",
    season: "",
    volume: "",
    price: "1만원 이하",
    imageUrl: "/images/cookie1.jpg",
  },
  {
    id: 17,
    name: "스타벅스 선물세트 A",
    category: "세트",
    category1: "선물세트",
    category2: "",
    season: "겨울 한정",
    volume: "",
    price: "2만원 이상",
    imageUrl: "/images/set1.jpg",
  },
  {
    id: 18,
    name: "디저트 세트",
    category: "세트",
    category1: "디저트세트",
    category2: "",
    season: "여름 한정",
    volume: "",
    price: "2만원 이상",
    imageUrl: "/images/set2.jpg",
  },
  {
    id: 19,
    name: "봄맞이 커플 머그 세트",
    category: "머그/컵",
    category1: "머그",
    category2: "세라믹",
    season: "봄 기획전",
    volume: "350ml",
    price: "2만원 이상",
    imageUrl: "/images/mug3.jpg",
  },
  {
    id: 20,
    name: "프리미엄 보온 텀블러",
    category: "텀블러/보온병",
    category1: "보온",
    category2: "1L 이상",
    season: "겨울 한정",
    volume: "500ml 이상",
    price: "2만원 이상",
    imageUrl: "/images/tumbler5.jpg",
  },
];
